### ISSUE TITLE
Add **kwargs support

### ISSUE THREAD

**Issue by rrfreimuth** [InformaticsGenomicMedicine/DraftCoreDataModel#1]
https://github.com/InformaticsGenomicMedicine/DraftCoreDataModel/blob/79450932a44ee677816f9c02e6f5660ea03e5ec1/src/core_variant.py#L7C1-L9C94

Please add **kwargs to the end of the input params so if a user passes an attribute not listed it is still captured. This can also be used as an easy way to save a copy of all of the input params at once.

**Comment by SalemBajjali** [comment]
Added **kwargs: 

https://github.com/InformaticsGenomicMedicine/DraftCoreDataModel/blob/66f815799c6c614970c4caed71740a6bd41ce2e6/src/core_variant.py#L7-L41

**Comment by SalemBajjali** [comment]
Reviewed with @rrfreimuth. renamed extra with kwargs
