### ISSUE TITLE
Class attributes should contain normalized values

### ISSUE THREAD

**Issue by rrfreimuth** [InformaticsGenomicMedicine/DraftCoreDataModel#10]
https://github.com/InformaticsGenomicMedicine/DraftCoreDataModel/blob/79450932a44ee677816f9c02e6f5660ea03e5ec1/src/core_variant.py#L11-L22

The assignment of the class attributes should be done after the original values are copied (in `self.initParamValues`), and the value should be the output of the appropriate validation method.

`self.origCoordSystem = self._validate_origCoordSystem(origCoordSystem)` is the right idea
`self.seqType = seqType` should be `self.seqType = self._validate_seqType(seqType)`

**Comment by SalemBajjali** [comment]
code edited here: 

https://github.com/InformaticsGenomicMedicine/DraftCoreDataModel/blob/66f815799c6c614970c4caed71740a6bd41ce2e6/src/core_variant.py#L26-L41

**Comment by SalemBajjali** [comment]
@rrfreimuth Reviewed via zoom meeting. Good to close.
