### ISSUE TITLE
Allow Chr in chrom

### ISSUE THREAD

**Issue by rrfreimuth** [InformaticsGenomicMedicine/DraftCoreDataModel#11]
https://github.com/InformaticsGenomicMedicine/DraftCoreDataModel/blob/79450932a44ee677816f9c02e6f5660ea03e5ec1/src/core_variant.py#L179C19-L180

If we're going to check the value at this level of granularity, we might as well support formats like "Chr 2" as well. Please add a regex to first match the pattern `^chr\s*([0-9a-z]+)$` (case insensitive) and then check the captured group against the list of allowed values.

**Comment by SalemBajjali** [comment]
Add support to chr format: 

https://github.com/InformaticsGenomicMedicine/DraftCoreDataModel/blob/66f815799c6c614970c4caed71740a6bd41ce2e6/src/core_variant.py#L305-L336

**Comment by SalemBajjali** [comment]
@rrfreimuth review via zoom. Looks good!
