### ISSUE TITLE
Genome build syntax is too strict

### ISSUE THREAD

**Issue by rrfreimuth** [InformaticsGenomicMedicine/DraftCoreDataModel#12]
https://github.com/InformaticsGenomicMedicine/DraftCoreDataModel/blob/79450932a44ee677816f9c02e6f5660ea03e5ec1/src/core_variant.py#L200C14-L200C14

The genome build regex must allow:
GRCh38.p14
GRCh38
T2T-CHM13
NCBI Build 36.1
(and probably others)

It might be easier to just check for empty/non-empty for now. If we get to a point where we try to normalize it then we can try to work through the details.

**Comment by SalemBajjali** [comment]
I removed the regular expression in the validation step and just allowed it for the user to input a string or None. If we plan to change this as you noted above we can come and revisit it at a later time. 

https://github.com/InformaticsGenomicMedicine/DraftCoreDataModel/blob/6d7818ca238167fc604b02917775c482f5af7490/src/core_variant.py#L346-L365

**Comment by SalemBajjali** [comment]
@rrfreimuth reviewed via zoom.
