### ISSUE TITLE
Determine validation requirements for sequence IDs

### ISSUE THREAD

**Issue by rrfreimuth** [InformaticsGenomicMedicine/DraftCoreDataModel#13]
https://github.com/InformaticsGenomicMedicine/DraftCoreDataModel/blob/79450932a44ee677816f9c02e6f5660ea03e5ec1/src/core_variant.py#L208-L209

Should we force sequence IDs to be of a particular syntax, or simply accept any string (which would allow local IDs to be used)?

**Comment by SalemBajjali** [comment]
@rrfreimuth, we plan to leave it as a string. Will plan to review later.
