### ISSUE TITLE
Return structure for normalized values

### ISSUE THREAD

**Issue by rrfreimuth** [InformaticsGenomicMedicine/DraftCoreDataModel#14]
https://github.com/InformaticsGenomicMedicine/DraftCoreDataModel/blob/79450932a44ee677816f9c02e6f5660ea03e5ec1/src/core_variant.py#L49C30-L49C30

The class should have a method that returns the public attributes (which should be already set to normalized values) for an instantiated object. Examples of methods could include:
`def __repr__(self):` (returned structure should be able to be passed directly into init() to create a new object)
`def as_dict(self):` (return values as a simple dictionary)
`def as_json(self):` (returned structure could be good for printing)

**Comment by SalemBajjali** [comment]
Method have been added: 
https://github.com/InformaticsGenomicMedicine/DraftCoreDataModel/blob/6d7818ca238167fc604b02917775c482f5af7490/src/core_variant.py#L43-L69

**Comment by SalemBajjali** [comment]
@rrfreimuth reviewed via zoom.
