### ISSUE TITLE
Remove defaults from db connection

### ISSUE THREAD

**Issue by rrfreimuth** [InformaticsGenomicMedicine/DraftCoreDataModel#15]
https://github.com/InformaticsGenomicMedicine/DraftCoreDataModel/blob/79450932a44ee677816f9c02e6f5660ea03e5ec1/src/database_extract.py#L7C56-L15

Please remove the hard-coded defaults from the code. An alternative option is to put them in a local config file that is read at runtime. If args are not passed, the code could look for that file and load it if found. This provides flexibility and convenience without polluting the codebase with local config info.

**Comment by SalemBajjali** [comment]
This is hard coded for my personal local machine, this will change once the database is set up.

**Comment by SalemBajjali** [comment]
removed hard coded values:

https://github.com/InformaticsGenomicMedicine/DraftCoreDataModel/blob/66f815799c6c614970c4caed71740a6bd41ce2e6/src/database/database_extract.py#L7-L13

**Comment by SalemBajjali** [comment]
@rrfreimuth reviewed via zoom.
