### ISSUE TITLE
Make some params optional

### ISSUE THREAD

**Issue by rrfreimuth** [InformaticsGenomicMedicine/DraftCoreDataModel#3]
https://github.com/InformaticsGenomicMedicine/DraftCoreDataModel/blob/79450932a44ee677816f9c02e6f5660ea03e5ec1/src/core_variant.py#L7-L9

These params should be optional:
allelicState:str,
geneSymbol:str
hgncId:int

**Comment by SalemBajjali** [comment]
Made allelicState, geneSymbol and hgncid as optinal params:
https://github.com/InformaticsGenomicMedicine/DraftCoreDataModel/blob/66f815799c6c614970c4caed71740a6bd41ce2e6/src/core_variant.py#L7-L10

**Comment by SalemBajjali** [comment]
Reviewed with @rrfreimuth.
