### ISSUE TITLE
Use "not in" operator

### ISSUE THREAD

**Issue by rrfreimuth** [InformaticsGenomicMedicine/DraftCoreDataModel#5]
https://github.com/InformaticsGenomicMedicine/DraftCoreDataModel/blob/79450932a44ee677816f9c02e6f5660ea03e5ec1/src/core_variant.py#L94C6-L94C6

Please change `if not value in set` to `if value not in set`. The first will work, but it is more pythonic to use the `not in` operator as [documented here](https://docs.python.org/3/reference/expressions.html#membership-test-operations).  Please change the linked conditional statement and then search the code for any others that need to be updated as well.

**Comment by SalemBajjali** [comment]
Changed syntax to "if value not in ..". Not going to highlight ever change but these changes were made in core_variant.py module that is currently in the issue-dev-sb branch.

**Comment by SalemBajjali** [comment]
Reviewed with @rrfreimuth.
