### ISSUE TITLE
Change hard-coding to dynamic list

### ISSUE THREAD

**Issue by rrfreimuth** [InformaticsGenomicMedicine/DraftCoreDataModel#6]
https://github.com/InformaticsGenomicMedicine/DraftCoreDataModel/blob/79450932a44ee677816f9c02e6f5660ea03e5ec1/src/core_variant.py#L95C83-L95C83

Replace the hard-coded list in the error message with a run-time expansion of the allowed values array. This will facilitate maintenance by ensuring the content is always in sync and doesn't need to be changed in more than 1 place.

Please change the linked code and then search for any other similar instances that need to be updated.

**Comment by SalemBajjali** [comment]
Fixed throughout the module:

https://github.com/InformaticsGenomicMedicine/DraftCoreDataModel/blob/66f815799c6c614970c4caed71740a6bd41ce2e6/src/core_variant.py#L131

**Comment by SalemBajjali** [comment]
Reviewed with @rrfreimuth.
