### ISSUE TITLE
Support for numeric SPDI ref/alt

### ISSUE THREAD

**Issue by rrfreimuth** [InformaticsGenomicMedicine/DraftCoreDataModel#8]
https://github.com/InformaticsGenomicMedicine/DraftCoreDataModel/blob/79450932a44ee677816f9c02e6f5660ea03e5ec1/src/core_variant.py#L160C31-L160C31

It sounds like SPDI permits a shorthand notation for ref and alt. Please explain, add links, and/or include examples to illustrate. I'm thinking this is going to need to be a separate validation routine, if we choose to support it.

**Comment by SalemBajjali** [comment]
Reference: https://www.biorxiv.org/content/10.1101/537449v3.full.pdf

On page 5 and 6
- (D)eletion: (a non-negative integer) deletion length, i.e. the reference allele length
- Table 1: SPDI representation for three simple variant types. 

Example: 
NC_000001.10:12345:0:C
NC_000001.11:930328:AA:

**Comment by rrfreimuth** [comment]
Please confirm my understanding.

NC_000001.10:12345:0:C => means delete 0 residues, insert a C
NC_000001.11:930328:AA: => means delete the AA, insert nothing

**Comment by SalemBajjali** [comment]
Yes your understanding is correct:

Here is an example break down from the reference above.
SPDI expression: NG_012345.1:4:1: 

position(1-based): 123456789
reference: ATAC**_G_**ACTG
alternate: ATAC-ACTG 

Deletion: 1 or G
Inserttion: 0 or (empty)

**Comment by SalemBajjali** [comment]
Reviewed with @rrfreimuth. Code looks correct but leaving open for pending more test.

**Comment by SalemBajjali** [comment]
Reviewed via zoom @rrfreimuth. Looked over test/test_spdi files.
