### ISSUE TITLE
Add values to error message

### ISSUE THREAD

**Issue by rrfreimuth** [InformaticsGenomicMedicine/DraftCoreDataModel#9]
https://github.com/InformaticsGenomicMedicine/DraftCoreDataModel/blob/79450932a44ee677816f9c02e6f5660ea03e5ec1/src/core_variant.py#L143C19-L143C19

Please add the values for `start` and `end` to the error message

**Comment by SalemBajjali** [comment]
Edited here:

https://github.com/InformaticsGenomicMedicine/DraftCoreDataModel/blob/66f815799c6c614970c4caed71740a6bd41ce2e6/src/core_variant.py#L239-L240

**Comment by SalemBajjali** [comment]
Reviewed with @rrfreimuth.
